//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spur.Resources {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spur.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutTitle {
            get { return ResourceManager.GetString("AboutTitle", resourceCulture); }
        }
        
        public static string ActionsCategory {
            get { return ResourceManager.GetString("ActionsCategory", resourceCulture); }
        }
        
        public static string AddOnsSettings {
            get { return ResourceManager.GetString("AddOnsSettings", resourceCulture); }
        }
        
        public static string AiSettings {
            get { return ResourceManager.GetString("AiSettings", resourceCulture); }
        }
        
        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }
        
        public static string CheckForUpdates {
            get { return ResourceManager.GetString("CheckForUpdates", resourceCulture); }
        }
        
        public static string ClearHistory {
            get { return ResourceManager.GetString("ClearHistory", resourceCulture); }
        }
        
        public static string ClipboardCategory {
            get { return ResourceManager.GetString("ClipboardCategory", resourceCulture); }
        }
        
        public static string Close {
            get { return ResourceManager.GetString("Close", resourceCulture); }
        }
        
        public static string Copy {
            get { return ResourceManager.GetString("Copy", resourceCulture); }
        }
        
        public static string Delete {
            get { return ResourceManager.GetString("Delete", resourceCulture); }
        }
        
        public static string FilesCategory {
            get { return ResourceManager.GetString("FilesCategory", resourceCulture); }
        }
        
        public static string GeneralSettings {
            get { return ResourceManager.GetString("GeneralSettings", resourceCulture); }
        }
        
        public static string NoResults {
            get { return ResourceManager.GetString("NoResults", resourceCulture); }
        }
        
        public static string Pin {
            get { return ResourceManager.GetString("Pin", resourceCulture); }
        }
        
        public static string Save {
            get { return ResourceManager.GetString("Save", resourceCulture); }
        }
        
        public static string SearchPlaceholder {
            get { return ResourceManager.GetString("SearchPlaceholder", resourceCulture); }
        }
        
        public static string SearchSettings {
            get { return ResourceManager.GetString("SearchSettings", resourceCulture); }
        }
        
        public static string SettingsTitle {
            get { return ResourceManager.GetString("SettingsTitle", resourceCulture); }
        }
        
        public static string Unpin {
            get { return ResourceManager.GetString("Unpin", resourceCulture); }
        }
    }
}